version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: jetbay-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: jetbay_user
      POSTGRES_PASSWORD: jetbay_password
      POSTGRES_DB: jetbay_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    container_name: jetbay-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: always

  minio:
    image: minio/minio:RELEASE.2024-01-28T22-35-53Z
    container_name: jetbay-minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_password
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: always

  mailpit:
    image: axllent/mailpit:v1.21
    container_name: jetbay-mailpit
    ports:
      - '1025:1025'
      - '8025:8025'
    restart: always

volumes:
  postgres_data:
  redis_data:
  minio_data:
