import {
  ForbiddenException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import PDFDocument from 'pdfkit';
import { PrismaService } from '../prisma/prisma.service';

@Injectable()
export class DocumentService {
  constructor(private readonly prisma: PrismaService) {}

  private async findOwnedDocument(id: number, userId: number) {
    const doc = await this.prisma.document.findUnique({
      where: { id },
      include: {
        booking: {
          include: {
            user: true,
            quoteOffer: { include: { quoteRequest: true } },
          },
        },
      },
    });
    if (!doc) throw new NotFoundException(`Document ${id} not found`);
    if (doc.booking.userId !== userId) {
      throw new ForbiddenException('You do not own this document');
    }
    return doc;
  }

  async getCharterAgreementHtml(id: number, userId: number): Promise<string> {
    const doc = await this.findOwnedDocument(id, userId);

    const user = doc.booking.user;
    const signer =
      [user.firstName, user.lastName].filter(Boolean).join(' ') || user.email;

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Charter Agreement #${doc.id}</title>
  <style>
    body { font-family: Georgia, serif; max-width: 720px; margin: 40px auto; color: #1a1a1a; line-height: 1.6; }
    h1 { color: #0b1f33; border-bottom: 2px solid #c9a84c; padding-bottom: 8px; }
    .meta { color: #555; font-size: 14px; margin-bottom: 24px; }
    .section { margin: 20px 0; }
    .footer { margin-top: 48px; font-size: 13px; color: #666; }
  </style>
</head>
<body>
  <h1>Private Jet Charter Agreement</h1>
  <p class="meta">Document #${doc.id} · Booking #${doc.bookingId} · Policy ${doc.policyVersion}</p>
  <div class="section">
    <p>This Charter Agreement ("Agreement") is entered into between <strong>JetVina Private Jet Charter</strong>
    and <strong>${signer}</strong> (${user.email}) for booking reference <strong>#${doc.bookingId}</strong>.</p>
    <p>Status: <strong>${doc.status}</strong></p>
  </div>
  <div class="section">
    <h2>Terms &amp; Conditions</h2>
    <ol>
      <li>Charter services are subject to aircraft availability and operational approval.</li>
      <li>Payment must be received before departure unless otherwise agreed in writing.</li>
      <li>Cancellation fees apply per the platform cancellation policy in effect at time of booking.</li>
      <li>Passenger manifest and identification must be provided 24 hours prior to departure.</li>
    </ol>
  </div>
  <p class="footer">Generated by JetVina Platform · ${new Date().toISOString().slice(0, 10)}</p>
</body>
</html>`;
  }

  async generateCharterAgreementPdf(id: number, userId: number): Promise<Buffer> {
    const doc = await this.findOwnedDocument(id, userId);

    const user = doc.booking.user;
    const signer =
      [user.firstName, user.lastName].filter(Boolean).join(' ') || user.email;

    return new Promise((resolve, reject) => {
      const pdf = new PDFDocument({ margin: 50 });
      const chunks: Buffer[] = [];
      pdf.on('data', (chunk: Buffer) => chunks.push(chunk));
      pdf.on('end', () => resolve(Buffer.concat(chunks)));
      pdf.on('error', reject);

      pdf
        .fontSize(20)
        .text('Private Jet Charter Agreement', { underline: true });
      pdf.moveDown();
      pdf.fontSize(11).fillColor('#444');
      pdf.text(
        `Document #${doc.id} · Booking #${doc.bookingId} · Policy ${doc.policyVersion}`,
      );
      pdf.moveDown();
      pdf.fillColor('#000').fontSize(12);
      pdf.text(
        `This Agreement is between JetVina Private Jet Charter and ${signer} (${user.email}) for booking #${doc.bookingId}.`,
      );
      pdf.moveDown();
      pdf.text(`Status: ${doc.status}`);
      pdf.moveDown();
      pdf.fontSize(14).text('Terms & Conditions');
      pdf.fontSize(11);
      const terms = [
        'Charter services are subject to aircraft availability and operational approval.',
        'Payment must be received before departure unless otherwise agreed in writing.',
        'Cancellation fees apply per the platform cancellation policy.',
        'Passenger manifest must be provided 24 hours prior to departure.',
      ];
      terms.forEach((t, i) => pdf.text(`${i + 1}. ${t}`));
      pdf.moveDown(2);
      pdf
        .fontSize(10)
        .fillColor('#666')
        .text(
          `Generated ${new Date().toISOString().slice(0, 10)} · JetVina Platform`,
        );
      pdf.end();
    });
  }

  /**
   * Word 2003 XML flat document — opens in Microsoft Word / LibreOffice
   * without adding a DOCX zip dependency (báo giá DoD: xuất Word/PDF).
   */
  async generateCharterAgreementWord(id: number, userId: number): Promise<Buffer> {
    const doc = await this.findOwnedDocument(id, userId);

    const user = doc.booking.user;
    const signer =
      [user.firstName, user.lastName].filter(Boolean).join(' ') || user.email;
    const esc = (s: string) =>
      s
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;');

    const paragraphs = [
      'Private Jet Charter Agreement',
      `Document #${doc.id} · Booking #${doc.bookingId} · Policy ${doc.policyVersion}`,
      `This Agreement is between JetVina Private Jet Charter and ${signer} (${user.email}) for booking #${doc.bookingId}.`,
      `Status: ${doc.status}`,
      'Terms & Conditions',
      '1. Charter services are subject to aircraft availability and operational approval.',
      '2. Payment must be received before departure unless otherwise agreed in writing.',
      '3. Cancellation fees apply per the platform cancellation policy.',
      '4. Passenger manifest must be provided 24 hours prior to departure.',
      `Generated ${new Date().toISOString().slice(0, 10)} · JetVina Platform`,
    ];

    const body = paragraphs
      .map(
        (p, i) =>
          `<w:p><w:r><w:rPr>${i === 0 || i === 4 ? '<w:b/>' : ''}<w:sz w:val="${i === 0 ? 28 : 22}"/></w:rPr><w:t>${esc(p)}</w:t></w:r></w:p>`,
      )
      .join('');

    const xml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?mso-application progid="Word.Document"?>
<w:wordDocument xmlns:w="http://schemas.microsoft.com/office/word/2003/wordml">
  <w:body>${body}</w:body>
</w:wordDocument>`;

    return Buffer.from(xml, 'utf8');
  }
}
