import { Injectable, NotFoundException } from '@nestjs/common';
import PDFDocument from 'pdfkit';
import { PrismaService } from '../prisma/prisma.service';

@Injectable()
export class DocumentService {
  constructor(private readonly prisma: PrismaService) {}

  async getCharterAgreementHtml(id: number): Promise<string> {
    const doc = await this.prisma.document.findUnique({
      where: { id },
      include: {
        booking: {
          include: {
            user: true,
            quoteOffer: { include: { quoteRequest: true } },
          },
        },
      },
    });
    if (!doc) throw new NotFoundException(`Document ${id} not found`);

    const user = doc.booking.user;
    const signer = [user.firstName, user.lastName].filter(Boolean).join(' ') || user.email;

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Charter Agreement #${doc.id}</title>
  <style>
    body { font-family: Georgia, serif; max-width: 720px; margin: 40px auto; color: #1a1a1a; line-height: 1.6; }
    h1 { color: #0b1f33; border-bottom: 2px solid #c9a84c; padding-bottom: 8px; }
    .meta { color: #555; font-size: 14px; margin-bottom: 24px; }
    .section { margin: 20px 0; }
    .footer { margin-top: 48px; font-size: 13px; color: #666; }
  </style>
</head>
<body>
  <h1>Private Jet Charter Agreement</h1>
  <p class="meta">Document #${doc.id} · Booking #${doc.bookingId} · Policy ${doc.policyVersion}</p>
  <div class="section">
    <p>This Charter Agreement ("Agreement") is entered into between <strong>J-TA Private Jet Charter</strong>
    and <strong>${signer}</strong> (${user.email}) for booking reference <strong>#${doc.bookingId}</strong>.</p>
    <p>Status: <strong>${doc.status}</strong></p>
  </div>
  <div class="section">
    <h2>Terms &amp; Conditions</h2>
    <ol>
      <li>Charter services are subject to aircraft availability and operational approval.</li>
      <li>Payment must be received before departure unless otherwise agreed in writing.</li>
      <li>Cancellation fees apply per the J-TA cancellation policy in effect at time of booking.</li>
      <li>Passenger manifest and identification must be provided 24 hours prior to departure.</li>
    </ol>
  </div>
  <p class="footer">Generated by J-TA Platform · ${new Date().toISOString().slice(0, 10)}</p>
</body>
</html>`;
  }

  async generateCharterAgreementPdf(id: number): Promise<Buffer> {
    const doc = await this.prisma.document.findUnique({
      where: { id },
      include: { booking: { include: { user: true } } },
    });
    if (!doc) throw new NotFoundException(`Document ${id} not found`);

    const user = doc.booking.user;
    const signer = [user.firstName, user.lastName].filter(Boolean).join(' ') || user.email;

    return new Promise((resolve, reject) => {
      const pdf = new PDFDocument({ margin: 50 });
      const chunks: Buffer[] = [];
      pdf.on('data', (chunk: Buffer) => chunks.push(chunk));
      pdf.on('end', () => resolve(Buffer.concat(chunks)));
      pdf.on('error', reject);

      pdf.fontSize(20).text('Private Jet Charter Agreement', { underline: true });
      pdf.moveDown();
      pdf.fontSize(11).fillColor('#444');
      pdf.text(`Document #${doc.id} · Booking #${doc.bookingId} · Policy ${doc.policyVersion}`);
      pdf.moveDown();
      pdf.fillColor('#000').fontSize(12);
      pdf.text(
        `This Agreement is between J-TA Private Jet Charter and ${signer} (${user.email}) for booking #${doc.bookingId}.`,
      );
      pdf.moveDown();
      pdf.text(`Status: ${doc.status}`);
      pdf.moveDown();
      pdf.fontSize(14).text('Terms & Conditions');
      pdf.fontSize(11);
      const terms = [
        'Charter services are subject to aircraft availability and operational approval.',
        'Payment must be received before departure unless otherwise agreed in writing.',
        'Cancellation fees apply per the J-TA cancellation policy.',
        'Passenger manifest must be provided 24 hours prior to departure.',
      ];
      terms.forEach((t, i) => pdf.text(`${i + 1}. ${t}`));
      pdf.moveDown(2);
      pdf.fontSize(10).fillColor('#666').text(`Generated ${new Date().toISOString().slice(0, 10)} · J-TA Platform`);
      pdf.end();
    });
  }
}
