/** Global private-aviation airports — upserted by prisma seed */

export type AirportSeed = {
  iata: string;
  icao: string;
  name: string;
  city: string;
  country: string;
  countryCode?: string;
  countryName?: string;
  continentCode?: string;
  continentName?: string;
  timezone: string;
  latitude?: number;
  longitude?: number;
  landingFee?: number;
  parkingFee?: number;
  overnightFee?: number;
  handlingFee?: number;
  feeCurrency?: string;
};

export const GLOBAL_AIRPORT_SEEDS: AirportSeed[] = [
  // Vietnam
  {
    iata: 'SGN',
    icao: 'VVTS',
    name: 'Tan Son Nhat International Airport',
    city: 'Ho Chi Minh City',
    country: 'Vietnam',
    countryCode: 'VN',
    countryName: 'Vietnam',
    continentCode: 'AS',
    continentName: 'Asia',
    timezone: 'Asia/Ho_Chi_Minh',
    latitude: 10.8188,
    longitude: 106.6519,
    landingFee: 450,
    parkingFee: 200,
    overnightFee: 350,
    handlingFee: 500,
    feeCurrency: 'USD',
  },
  {
    iata: 'HAN',
    icao: 'VVNB',
    name: 'Noi Bai International Airport',
    city: 'Hanoi',
    country: 'Vietnam',
    countryCode: 'VN',
    countryName: 'Vietnam',
    continentCode: 'AS',
    continentName: 'Asia',
    timezone: 'Asia/Ho_Chi_Minh',
    latitude: 21.2212,
    longitude: 105.8072,
    landingFee: 420,
    parkingFee: 180,
    overnightFee: 320,
    handlingFee: 480,
    feeCurrency: 'USD',
  },
  {
    iata: 'CXR',
    icao: 'VVCR',
    name: 'Cam Ranh International Airport',
    city: 'Nha Trang',
    country: 'Vietnam',
    countryCode: 'VN',
    countryName: 'Vietnam',
    continentCode: 'AS',
    continentName: 'Asia',
    timezone: 'Asia/Ho_Chi_Minh',
  },
  {
    iata: 'DAD',
    icao: 'VVDN',
    name: 'Da Nang International Airport',
    city: 'Da Nang',
    country: 'Vietnam',
    countryCode: 'VN',
    countryName: 'Vietnam',
    continentCode: 'AS',
    continentName: 'Asia',
    timezone: 'Asia/Ho_Chi_Minh',
  },
  {
    iata: 'HUI',
    icao: 'VVPH',
    name: 'Phu Bai International Airport',
    city: 'Hue',
    country: 'Vietnam',
    countryCode: 'VN',
    countryName: 'Vietnam',
    continentCode: 'AS',
    continentName: 'Asia',
    timezone: 'Asia/Ho_Chi_Minh',
  },
  // China
  {
    iata: 'CAN',
    icao: 'ZGGG',
    name: 'Guangzhou Baiyun International Airport',
    city: 'Guangzhou',
    country: 'China',
    countryCode: 'CN',
    countryName: 'China',
    continentCode: 'AS',
    continentName: 'Asia',
    timezone: 'Asia/Shanghai',
    latitude: 23.3924,
    longitude: 113.2988,
    landingFee: 600,
    parkingFee: 250,
    overnightFee: 400,
    handlingFee: 550,
    feeCurrency: 'USD',
  },
  {
    iata: 'PVG',
    icao: 'ZSPD',
    name: 'Shanghai Pudong International Airport',
    city: 'Shanghai',
    country: 'China',
    countryCode: 'CN',
    countryName: 'China',
    continentCode: 'AS',
    continentName: 'Asia',
    timezone: 'Asia/Shanghai',
  },
  {
    iata: 'PEK',
    icao: 'ZBAA',
    name: 'Beijing Capital International Airport',
    city: 'Beijing',
    country: 'China',
    countryCode: 'CN',
    countryName: 'China',
    continentCode: 'AS',
    continentName: 'Asia',
    timezone: 'Asia/Shanghai',
  },
  // UK
  {
    iata: 'LTN',
    icao: 'EGGW',
    name: 'London Luton Airport',
    city: 'London',
    country: 'UK',
    countryCode: 'GB',
    countryName: 'United Kingdom',
    continentCode: 'EU',
    continentName: 'Europe',
    timezone: 'Europe/London',
  },
  {
    iata: 'FAB',
    icao: 'EGLF',
    name: 'Farnborough Airport',
    city: 'London',
    country: 'UK',
    countryCode: 'GB',
    countryName: 'United Kingdom',
    continentCode: 'EU',
    continentName: 'Europe',
    timezone: 'Europe/London',
  },
  {
    iata: 'LCY',
    icao: 'EGLC',
    name: 'London City Airport',
    city: 'London',
    country: 'UK',
    countryCode: 'GB',
    countryName: 'United Kingdom',
    continentCode: 'EU',
    continentName: 'Europe',
    timezone: 'Europe/London',
  },
  // France
  {
    iata: 'LBG',
    icao: 'LFPB',
    name: 'Paris Le Bourget Airport',
    city: 'Paris',
    country: 'France',
    countryCode: 'FR',
    countryName: 'France',
    continentCode: 'EU',
    continentName: 'Europe',
    timezone: 'Europe/Paris',
  },
  {
    iata: 'NCE',
    icao: 'LFMN',
    name: "Nice Cote d'Azur Airport",
    city: 'Nice',
    country: 'France',
    countryCode: 'FR',
    countryName: 'France',
    continentCode: 'EU',
    continentName: 'Europe',
    timezone: 'Europe/Paris',
  },
  {
    iata: 'MRS',
    icao: 'LFML',
    name: 'Marseille Provence Airport',
    city: 'Marseille',
    country: 'France',
    countryCode: 'FR',
    countryName: 'France',
    continentCode: 'EU',
    continentName: 'Europe',
    timezone: 'Europe/Paris',
  },
  {
    iata: 'TLS',
    icao: 'LFBO',
    name: 'Toulouse-Blagnac Airport',
    city: 'Toulouse',
    country: 'France',
    countryCode: 'FR',
    countryName: 'France',
    continentCode: 'EU',
    continentName: 'Europe',
    timezone: 'Europe/Paris',
  },
  {
    iata: 'LYS',
    icao: 'LFLL',
    name: 'Lyon-Saint Exupery Airport',
    city: 'Lyon',
    country: 'France',
    countryCode: 'FR',
    countryName: 'France',
    continentCode: 'EU',
    continentName: 'Europe',
    timezone: 'Europe/Paris',
  },
  // Switzerland
  {
    iata: 'GVA',
    icao: 'LSGG',
    name: 'Geneva Airport',
    city: 'Geneva',
    country: 'Switzerland',
    countryCode: 'CH',
    countryName: 'Switzerland',
    continentCode: 'EU',
    continentName: 'Europe',
    timezone: 'Europe/Zurich',
  },
  {
    iata: 'ZRH',
    icao: 'LSZH',
    name: 'Zurich Airport',
    city: 'Zurich',
    country: 'Switzerland',
    countryCode: 'CH',
    countryName: 'Switzerland',
    continentCode: 'EU',
    continentName: 'Europe',
    timezone: 'Europe/Zurich',
  },
  // USA
  {
    iata: 'VNY',
    icao: 'KVNY',
    name: 'Van Nuys Airport',
    city: 'Los Angeles',
    country: 'USA',
    countryCode: 'US',
    countryName: 'United States',
    continentCode: 'NA',
    continentName: 'North America',
    timezone: 'America/Los_Angeles',
  },
  {
    iata: 'LAS',
    icao: 'KLAS',
    name: 'Harry Reid International Airport',
    city: 'Las Vegas',
    country: 'USA',
    countryCode: 'US',
    countryName: 'United States',
    continentCode: 'NA',
    continentName: 'North America',
    timezone: 'America/Los_Angeles',
  },
  {
    iata: 'TEB',
    icao: 'KTEB',
    name: 'Teterboro Airport',
    city: 'New York',
    country: 'USA',
    countryCode: 'US',
    countryName: 'United States',
    continentCode: 'NA',
    continentName: 'North America',
    timezone: 'America/New_York',
  },
  {
    iata: 'OPF',
    icao: 'KOPF',
    name: 'Miami-Opa Locka Executive Airport',
    city: 'Miami',
    country: 'USA',
    countryCode: 'US',
    countryName: 'United States',
    continentCode: 'NA',
    continentName: 'North America',
    timezone: 'America/New_York',
  },
  {
    iata: 'IAD',
    icao: 'KIAD',
    name: 'Washington Dulles International Airport',
    city: 'Washington',
    country: 'USA',
    countryCode: 'US',
    countryName: 'United States',
    continentCode: 'NA',
    continentName: 'North America',
    timezone: 'America/New_York',
  },
  {
    iata: 'PBI',
    icao: 'KPBI',
    name: 'Palm Beach International Airport',
    city: 'Palm Beach',
    country: 'USA',
    countryCode: 'US',
    countryName: 'United States',
    continentCode: 'NA',
    continentName: 'North America',
    timezone: 'America/New_York',
  },
  {
    iata: 'DAL',
    icao: 'KDAL',
    name: 'Dallas Love Field',
    city: 'Dallas',
    country: 'USA',
    countryCode: 'US',
    countryName: 'United States',
    continentCode: 'NA',
    continentName: 'North America',
    timezone: 'America/Chicago',
  },
  {
    iata: 'APA',
    icao: 'KAPA',
    name: 'Centennial Airport',
    city: 'Denver',
    country: 'USA',
    countryCode: 'US',
    countryName: 'United States',
    continentCode: 'NA',
    continentName: 'North America',
    timezone: 'America/Denver',
  },
  {
    iata: 'SFO',
    icao: 'KSFO',
    name: 'San Francisco International Airport',
    city: 'San Francisco',
    country: 'USA',
    countryCode: 'US',
    countryName: 'United States',
    continentCode: 'NA',
    continentName: 'North America',
    timezone: 'America/Los_Angeles',
  },
  {
    iata: 'BOS',
    icao: 'KBOS',
    name: 'Boston Logan International Airport',
    city: 'Boston',
    country: 'USA',
    countryCode: 'US',
    countryName: 'United States',
    continentCode: 'NA',
    continentName: 'North America',
    timezone: 'America/New_York',
  },
  {
    iata: 'FLL',
    icao: 'KFLL',
    name: 'Fort Lauderdale International Airport',
    city: 'Fort Lauderdale',
    country: 'USA',
    countryCode: 'US',
    countryName: 'United States',
    continentCode: 'NA',
    continentName: 'North America',
    timezone: 'America/New_York',
  },
  // Asia-Pacific hubs
  {
    iata: 'SIN',
    icao: 'WSSS',
    name: 'Singapore Changi Airport',
    city: 'Singapore',
    country: 'Singapore',
    countryCode: 'SG',
    countryName: 'Singapore',
    continentCode: 'AS',
    continentName: 'Asia',
    timezone: 'Asia/Singapore',
  },
  {
    iata: 'HKG',
    icao: 'VHHH',
    name: 'Hong Kong International Airport',
    city: 'Hong Kong',
    country: 'Hong Kong',
    countryCode: 'HK',
    countryName: 'Hong Kong',
    continentCode: 'AS',
    continentName: 'Asia',
    timezone: 'Asia/Hong_Kong',
  },
  {
    iata: 'NRT',
    icao: 'RJAA',
    name: 'Narita International Airport',
    city: 'Tokyo',
    country: 'Japan',
    countryCode: 'JP',
    countryName: 'Japan',
    continentCode: 'AS',
    continentName: 'Asia',
    timezone: 'Asia/Tokyo',
  },
  {
    iata: 'HND',
    icao: 'RJTT',
    name: 'Tokyo Haneda Airport',
    city: 'Tokyo',
    country: 'Japan',
    countryCode: 'JP',
    countryName: 'Japan',
    continentCode: 'AS',
    continentName: 'Asia',
    timezone: 'Asia/Tokyo',
  },
  {
    iata: 'BKK',
    icao: 'VTBS',
    name: 'Suvarnabhumi Airport',
    city: 'Bangkok',
    country: 'Thailand',
    countryCode: 'TH',
    countryName: 'Thailand',
    continentCode: 'AS',
    continentName: 'Asia',
    timezone: 'Asia/Bangkok',
  },
  {
    iata: 'DXB',
    icao: 'OMDB',
    name: 'Dubai International Airport',
    city: 'Dubai',
    country: 'UAE',
    countryCode: 'AE',
    countryName: 'United Arab Emirates',
    continentCode: 'AS',
    continentName: 'Asia',
    timezone: 'Asia/Dubai',
  },
  // Europe
  {
    iata: 'FRA',
    icao: 'EDDF',
    name: 'Frankfurt Airport',
    city: 'Frankfurt',
    country: 'Germany',
    countryCode: 'DE',
    countryName: 'Germany',
    continentCode: 'EU',
    continentName: 'Europe',
    timezone: 'Europe/Berlin',
  },
  {
    iata: 'MUC',
    icao: 'EDDM',
    name: 'Munich Airport',
    city: 'Munich',
    country: 'Germany',
    countryCode: 'DE',
    countryName: 'Germany',
    continentCode: 'EU',
    continentName: 'Europe',
    timezone: 'Europe/Berlin',
  },
  {
    iata: 'MXP',
    icao: 'LIMC',
    name: 'Milan Malpensa Airport',
    city: 'Milan',
    country: 'Italy',
    countryCode: 'IT',
    countryName: 'Italy',
    continentCode: 'EU',
    continentName: 'Europe',
    timezone: 'Europe/Rome',
  },
  {
    iata: 'FCO',
    icao: 'LIRF',
    name: 'Rome Fiumicino Airport',
    city: 'Rome',
    country: 'Italy',
    countryCode: 'IT',
    countryName: 'Italy',
    continentCode: 'EU',
    continentName: 'Europe',
    timezone: 'Europe/Rome',
  },
  {
    iata: 'MAD',
    icao: 'LEMD',
    name: 'Adolfo Suarez Madrid-Barajas Airport',
    city: 'Madrid',
    country: 'Spain',
    countryCode: 'ES',
    countryName: 'Spain',
    continentCode: 'EU',
    continentName: 'Europe',
    timezone: 'Europe/Madrid',
  },
  {
    iata: 'BCN',
    icao: 'LEBL',
    name: 'Barcelona-El Prat Airport',
    city: 'Barcelona',
    country: 'Spain',
    countryCode: 'ES',
    countryName: 'Spain',
    continentCode: 'EU',
    continentName: 'Europe',
    timezone: 'Europe/Madrid',
  },
];
