export type HttpMethod = 'GET' | 'POST' | 'PATCH' | 'DELETE';

export type ApiEndpointDef = {
  method: HttpMethod;
  path: string;
  tag: string;
  summary: string;
  implemented: boolean;
  /** Method name in apps/web/src/lib/api.ts */
  webClientMethod?: string;
  /** Locale-prefixed web routes that consume this endpoint */
  webRoutes: string[];
  requiresAuth?: boolean;
};

export type WebPageDef = {
  route: string;
  name: string;
  kind: 'dynamic' | 'static' | 'auth';
  endpoints: string[];
  notes?: string;
};

/** Canonical key: METHOD /path (no query string) */
export function endpointKey(method: HttpMethod, path: string) {
  return `${method} ${path}`;
}

export const WEB_UI_PAGES: WebPageDef[] = [
  {
    route: '/{locale}',
    name: 'Home',
    kind: 'dynamic',
    endpoints: [
      'GET /fixed-price/routes',
      'GET /empty-legs',
      'GET /content/destinations',
      'GET /jet-card/plans',
      'POST /quotes/search-aircraft',
      'POST /quotes/request',
      'GET /airports/search',
    ],
  },
  {
    route: '/{locale}/news',
    name: 'News listing',
    kind: 'dynamic',
    endpoints: ['GET /content/news'],
  },
  {
    route: '/{locale}/news/{slug}',
    name: 'News article',
    kind: 'dynamic',
    endpoints: ['GET /content/news/:slug'],
  },
  {
    route: '/{locale}/blogs',
    name: 'Blogs listing',
    kind: 'dynamic',
    endpoints: ['GET /content/blogs'],
  },
  {
    route: '/{locale}/blogs/{slug}',
    name: 'Blog post',
    kind: 'dynamic',
    endpoints: ['GET /content/blogs/:slug'],
  },
  {
    route: '/{locale}/video-centre',
    name: 'Video centre',
    kind: 'dynamic',
    endpoints: ['GET /content/videos'],
  },
  {
    route: '/{locale}/fixed-price-charter',
    name: 'Fixed price routes',
    kind: 'dynamic',
    endpoints: ['GET /fixed-price/routes'],
  },
  {
    route: '/{locale}/fixed-price-charter/{slug}',
    name: 'Fixed price route detail',
    kind: 'dynamic',
    endpoints: [
      'GET /fixed-price/routes/:slug',
      'POST /fixed-price/quote',
      'POST /quotes/search-aircraft',
      'POST /quotes/request',
    ],
  },
  {
    route: '/{locale}/empty-leg',
    name: 'Empty legs listing',
    kind: 'dynamic',
    endpoints: ['GET /empty-legs', 'POST /empty-legs/alerts/subscribe'],
  },
  {
    route: '/{locale}/empty-leg-recommendation/{slug}',
    name: 'Empty leg detail',
    kind: 'dynamic',
    endpoints: ['GET /empty-legs/:slug', 'POST /empty-legs/:id/request'],
  },
  {
    route: '/{locale}/island-destinations',
    name: 'Island destinations',
    kind: 'dynamic',
    endpoints: ['GET /content/destinations'],
  },
  {
    route: '/{locale}/destination',
    name: 'Destinations hub',
    kind: 'dynamic',
    endpoints: ['GET /content/destinations', 'GET /content/destinations/:slug'],
  },
  {
    route: '/{locale}/jet-card',
    name: 'Jet Card',
    kind: 'dynamic',
    endpoints: ['GET /jet-card/plans', 'POST /jet-card/enquiries'],
  },
  {
    route: '/{locale}/travel-credit',
    name: 'Travel credits',
    kind: 'dynamic',
    endpoints: ['GET /travel-credits/packages', 'POST /travel-credits/enquiries'],
  },
  {
    route: '/{locale}/article/{slug}',
    name: 'Legal / CMS page',
    kind: 'dynamic',
    endpoints: ['GET /content/pages/:slug'],
  },
  {
    route: '/{locale}/login',
    name: 'Login',
    kind: 'auth',
    endpoints: ['POST /auth/login'],
  },
  {
    route: '/{locale}/register',
    name: 'Register',
    kind: 'auth',
    endpoints: ['POST /auth/register'],
  },
  {
    route: '/{locale}/account',
    name: 'My account',
    kind: 'auth',
    endpoints: ['GET /me', 'GET /bookings/my'],
  },
  {
    route: '/{locale}/global-partnership-program',
    name: 'Global partnership',
    kind: 'dynamic',
    endpoints: ['GET /partners/programs', 'POST /partners/applications'],
  },
  {
    route: '/{locale}/world-cup-2026-private-jet-booking',
    name: 'World Cup booking',
    kind: 'dynamic',
    endpoints: ['GET /campaigns/world-cup/matches', 'POST /campaigns/world-cup/quotes'],
  },
  {
    route: '/{locale}/world-cup-final-2026-private-jet-charter',
    name: 'World Cup final charter',
    kind: 'dynamic',
    endpoints: ['GET /campaigns/world-cup/matches', 'POST /campaigns/world-cup/quotes'],
  },
  {
    route: '/{locale}/private-jet-charter',
    name: 'Private jet charter',
    kind: 'static',
    endpoints: ['POST /quotes/search-aircraft', 'POST /quotes/request', 'GET /airports/search'],
    notes: 'Static copy; quote widget calls quote APIs',
  },
  {
    route: '/{locale}/corporate-air-charter',
    name: 'Corporate charter',
    kind: 'static',
    endpoints: ['POST /quotes/search-aircraft', 'POST /quotes/request'],
  },
  {
    route: '/{locale}/group-air-charter',
    name: 'Group charter',
    kind: 'static',
    endpoints: ['POST /quotes/search-aircraft', 'POST /quotes/request'],
  },
  {
    route: '/{locale}/event-air-charter',
    name: 'Event charter',
    kind: 'static',
    endpoints: ['POST /quotes/search-aircraft', 'POST /quotes/request'],
  },
  {
    route: '/{locale}/air-ambulance',
    name: 'Air ambulance',
    kind: 'static',
    endpoints: ['POST /quotes/search-aircraft', 'POST /quotes/request'],
  },
  {
    route: '/{locale}/pet-travel',
    name: 'Pet travel',
    kind: 'static',
    endpoints: ['POST /quotes/search-aircraft', 'POST /quotes/request'],
  },
  {
    route: '/{locale}/booking-process',
    name: 'Booking process',
    kind: 'static',
    endpoints: [],
  },
  {
    route: '/{locale}/about-us',
    name: 'About us',
    kind: 'static',
    endpoints: [],
  },
  {
    route: '/{locale}/jetbay-private-jet-app',
    name: 'Mobile app',
    kind: 'static',
    endpoints: [],
  },
];

export const API_UI_REGISTRY: ApiEndpointDef[] = [
  {
    method: 'GET',
    path: '/airports/search',
    tag: 'Airports',
    summary: 'Airport autocomplete for quote widget',
    implemented: true,
    webClientMethod: 'searchAirports',
    webRoutes: ['/{locale}', '/{locale}/private-jet-charter'],
  },
  {
    method: 'GET',
    path: '/fixed-price/routes',
    tag: 'Fixed Price',
    summary: 'List fixed-price charter routes',
    implemented: true,
    webClientMethod: 'getFixedPriceRoutes',
    webRoutes: ['/{locale}', '/{locale}/fixed-price-charter'],
  },
  {
    method: 'GET',
    path: '/fixed-price/routes/:slug',
    tag: 'Fixed Price',
    summary: 'Fixed-price route detail',
    implemented: true,
    webClientMethod: 'getFixedPriceRoute',
    webRoutes: ['/{locale}/fixed-price-charter/{slug}'],
  },
  {
    method: 'POST',
    path: '/fixed-price/quote',
    tag: 'Fixed Price',
    summary: 'Book / quote a fixed-price route',
    implemented: true,
    webClientMethod: 'requestFixedPriceQuote',
    webRoutes: ['/{locale}/fixed-price-charter/{slug}'],
  },
  {
    method: 'GET',
    path: '/empty-legs',
    tag: 'Empty Legs',
    summary: 'List empty leg deals',
    implemented: true,
    webClientMethod: 'getEmptyLegs',
    webRoutes: ['/{locale}', '/{locale}/empty-leg'],
  },
  {
    method: 'GET',
    path: '/empty-legs/:slug',
    tag: 'Empty Legs',
    summary: 'Empty leg detail by slug',
    implemented: true,
    webClientMethod: 'getEmptyLeg',
    webRoutes: ['/{locale}/empty-leg-recommendation/{slug}'],
  },
  {
    method: 'POST',
    path: '/empty-legs/alerts/subscribe',
    tag: 'Empty Legs',
    summary: 'Subscribe to empty leg alerts',
    implemented: true,
    webClientMethod: 'subscribeEmptyLegAlerts',
    webRoutes: ['/{locale}/empty-leg'],
  },
  {
    method: 'POST',
    path: '/empty-legs/:id/request',
    tag: 'Empty Legs',
    summary: 'Request booking for an empty leg',
    implemented: true,
    webClientMethod: 'requestEmptyLeg',
    webRoutes: ['/{locale}/empty-leg-recommendation/{slug}'],
  },
  {
    method: 'GET',
    path: '/content/news',
    tag: 'Content',
    summary: 'News articles list',
    implemented: true,
    webClientMethod: 'getNews',
    webRoutes: ['/{locale}/news'],
  },
  {
    method: 'GET',
    path: '/content/news/:slug',
    tag: 'Content',
    summary: 'News article detail',
    implemented: true,
    webClientMethod: 'getNewsArticle',
    webRoutes: ['/{locale}/news/{slug}'],
  },
  {
    method: 'GET',
    path: '/content/blogs',
    tag: 'Content',
    summary: 'Blog posts list',
    implemented: true,
    webClientMethod: 'getBlogs',
    webRoutes: ['/{locale}/blogs'],
  },
  {
    method: 'GET',
    path: '/content/blogs/:slug',
    tag: 'Content',
    summary: 'Blog post detail',
    implemented: true,
    webClientMethod: 'getBlog',
    webRoutes: ['/{locale}/blogs/{slug}'],
  },
  {
    method: 'GET',
    path: '/content/videos',
    tag: 'Content',
    summary: 'Video centre list',
    implemented: true,
    webClientMethod: 'getVideos',
    webRoutes: ['/{locale}/video-centre'],
  },
  {
    method: 'GET',
    path: '/content/destinations',
    tag: 'Content',
    summary: 'Destination guides by category',
    implemented: true,
    webClientMethod: 'getDestinations',
    webRoutes: ['/{locale}', '/{locale}/destination', '/{locale}/island-destinations'],
  },
  {
    method: 'GET',
    path: '/content/destinations/:slug',
    tag: 'Content',
    summary: 'Single destination by slug',
    implemented: true,
    webClientMethod: 'getDestination',
    webRoutes: ['/{locale}/destination'],
  },
  {
    method: 'GET',
    path: '/content/pages/:slug',
    tag: 'Content',
    summary: 'CMS / legal static pages',
    implemented: true,
    webClientMethod: 'getContentPage',
    webRoutes: ['/{locale}/article/{slug}'],
  },
  {
    method: 'POST',
    path: '/newsletter/subscribe',
    tag: 'Content',
    summary: 'Footer newsletter signup',
    implemented: true,
    webClientMethod: 'subscribeNewsletter',
    webRoutes: ['/{locale}'],
  },
  {
    method: 'POST',
    path: '/quotes/search-aircraft',
    tag: 'Quotes',
    summary: 'Search aircraft for quote widget',
    implemented: true,
    webClientMethod: 'searchAircraft',
    webRoutes: ['/{locale}'],
  },
  {
    method: 'POST',
    path: '/quotes/request',
    tag: 'Quotes',
    summary: 'Submit charter quote request',
    implemented: true,
    webClientMethod: 'requestQuote',
    webRoutes: ['/{locale}'],
  },
  {
    method: 'GET',
    path: '/campaigns/world-cup/matches',
    tag: 'Campaigns',
    summary: 'World Cup 2026 match schedule',
    implemented: true,
    webClientMethod: 'getWorldCupMatches',
    webRoutes: [
      '/{locale}/world-cup-2026-private-jet-booking',
      '/{locale}/world-cup-final-2026-private-jet-charter',
    ],
  },
  {
    method: 'POST',
    path: '/campaigns/world-cup/quotes',
    tag: 'Campaigns',
    summary: 'World Cup charter quote request',
    implemented: true,
    webClientMethod: 'requestWorldCupQuote',
    webRoutes: [
      '/{locale}/world-cup-2026-private-jet-booking',
      '/{locale}/world-cup-final-2026-private-jet-charter',
    ],
  },
  {
    method: 'GET',
    path: '/jet-card/plans',
    tag: 'Jet Card',
    summary: 'Jet Card membership tiers',
    implemented: true,
    webClientMethod: 'getJetCardPlans',
    webRoutes: ['/{locale}', '/{locale}/jet-card'],
  },
  {
    method: 'POST',
    path: '/jet-card/enquiries',
    tag: 'Jet Card',
    summary: 'Jet Card membership enquiry',
    implemented: true,
    webClientMethod: 'submitJetCardEnquiry',
    webRoutes: ['/{locale}/jet-card'],
  },
  {
    method: 'GET',
    path: '/travel-credits/packages',
    tag: 'Travel Credits',
    summary: 'Travel credit packages',
    implemented: true,
    webClientMethod: 'getTravelCreditPackages',
    webRoutes: ['/{locale}/travel-credit'],
  },
  {
    method: 'POST',
    path: '/travel-credits/enquiries',
    tag: 'Travel Credits',
    summary: 'Travel credit purchase enquiry',
    implemented: true,
    webClientMethod: 'submitTravelCreditEnquiry',
    webRoutes: ['/{locale}/travel-credit'],
  },
  {
    method: 'GET',
    path: '/partners/programs',
    tag: 'Partners',
    summary: 'Global partnership program tiers',
    implemented: true,
    webClientMethod: 'getPartnerPrograms',
    webRoutes: ['/{locale}/global-partnership-program'],
  },
  {
    method: 'POST',
    path: '/partners/applications',
    tag: 'Partners',
    summary: 'Submit partnership application',
    implemented: true,
    webClientMethod: 'submitPartnerApplication',
    webRoutes: ['/{locale}/global-partnership-program'],
  },
  {
    method: 'POST',
    path: '/auth/login',
    tag: 'Auth',
    summary: 'Email/password login',
    implemented: true,
    webClientMethod: 'login',
    webRoutes: ['/{locale}/login'],
  },
  {
    method: 'POST',
    path: '/auth/register',
    tag: 'Auth',
    summary: 'Create account',
    implemented: true,
    webClientMethod: 'register',
    webRoutes: ['/{locale}/register'],
  },
  {
    method: 'GET',
    path: '/me',
    tag: 'Auth',
    summary: 'Current user profile',
    implemented: true,
    webClientMethod: 'getMe',
    webRoutes: ['/{locale}/account'],
    requiresAuth: true,
  },
  {
    method: 'GET',
    path: '/bookings/my',
    tag: 'Bookings',
    summary: 'Authenticated user bookings',
    implemented: true,
    webClientMethod: 'getMyBookings',
    webRoutes: ['/{locale}/account'],
    requiresAuth: true,
  },
];
